<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fake.proto

namespace GPBMetadata;

use Google\Protobuf\Internal\DescriptorPool;

class Fake
{
    public static $is_initialized = false;

    public static function initOnce(): void
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }

        $pool->internalAddGeneratedFile(hex2bin(
            '0a5e0a0a66616b652e70726f746f1228536f66746f6e69632e4c61726176656c50726f746f6275664576656e74732e46616b6550726f746f221e0a0b46616b654d657373616765120f0a07636f6e74656e74180120012809620670726f746f33'
        ), true);

        static::$is_initialized = true;
    }
}
