name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-php-

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      run: composer install --prefer-dist --no-progress && composer run-script test
      with:
        php-version: '8.0'
        coverage: xdebug2
        extensions: xdebug3, pcntl, bcmath, protobuf
      env:
        COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
